FROM mcr.microsoft.com/dotnet/aspnet:7.0-alpine AS base
WORKDIR /app
EXPOSE 80/tcp

FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build
WORKDIR /src

COPY ./Solita.Bike.Shared ./Solita.Bike.Shared
COPY ./Solita.Bike.Api ./Solita.Bike.Api

RUN dotnet restore "Solita.Bike.Shared/Solita.Bike.Shared.csproj"
RUN dotnet restore "Solita.Bike.Api/Solita.Bike.Api.csproj"

WORKDIR "/src/."
RUN dotnet build "Solita.Bike.Api/Solita.Bike.Api.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "Solita.Bike.Api/Solita.Bike.Api.csproj" -c Release -o /app/publish
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
ENTRYPOINT ["dotnet", "Solita.Bike.Api.dll"]
